spring:
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRESQL_PASSWORD:admin}
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST:localhost}:${POSTGRESQL_SERVICE_PORT:5432}/${POSTGRESQL_DATABASE:asao-ms-users}
    username: ${POSTGRESQL_USER:postgres}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
  port : 8080